#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

mvn -q exec:java -f $DIR/crawler/pom.xml -Dexec.mainClass="org.insightcentre.nlp.saffron.crawler.SaffronCrawler" -Dexec.args="$*"
